#!/usr/bin/env bash
echo "Footprint generator by noytzach (c) 2021"

echo skill load \"$PWD/builder.ile\" > builder.scr.txt
echo skill changeWorkingDir \"$PWD\" >> builder.scr.txt
for g in *.xml
do
    echo skill LB_createFootprint \"$PWD/$g\" >> builder.scr.txt
    if [ -a ${g%%.*}.step ] 
    then
        echo scriptmode +i +n >> builder.scr.txt
        echo step pkg map >> builder.scr.txt
        echo setwindow form.pkgmap3d >>  builder.scr.txt
        echo FORM pkgmap3d stplist ${g%%.*}.step >> builder.scr.txt
        echo FORM pkgmap3d rotation_x 0 >> builder.scr.txt
        echo FORM pkgmap3d save_current >> builder.scr.txt
        echo FORM pkgmap3d done >> builder.scr.txt
        echo setwindow pcb >> builder.scr.txt
        echo save  >> builder.scr.txt
        echo fillin yes >> builder.scr.txt
    fi
done
echo exit >> builder.scr.txt

echo Creating footprints..
allegro -s builder.scr.txt
